# Generated by Django 2.1.4 on 2018-12-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.CharField(max_length=255)),
                ('bg_img', models.ImageField(upload_to='')),
                ('page_type', models.IntegerField()),
                ('button_text', models.CharField(max_length=255)),
                ('content_text', models.CharField(max_length=255)),
            ],
        ),
    ]
