# Generated by Django 2.1.4 on 2018-12-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181219_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalheader',
            name='bg_img',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='generalheader',
            name='button_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='generalheader',
            name='page_type',
            field=models.IntegerField(choices=[(0, 'HOME'), (1, 'ABOUT'), (2, 'CONTACT'), (3, 'DASHBOARD'), (4, 'LOGIN'), (5, 'SETTINGS'), (6, 'REGISTER')], default=0),
        ),
        migrations.AlterField(
            model_name='generalheader',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='generalheader',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
