# Generated by Django 2.1.4 on 2018-12-21 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_navbar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(upload_to='media')),
                ('bg_image', models.ImageField(upload_to='media')),
                ('occupation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='media')),
                ('icon_link', models.CharField(max_length=500)),
                ('footer_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=255)),
                ('post_subtitle', models.CharField(max_length=255)),
                ('publish_date', models.DateTimeField()),
                ('bg_img', models.ImageField(blank=True, null=True, upload_to='media')),
                ('content_text', models.CharField(max_length=255)),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Author')),
            ],
        ),
    ]
