# Generated by Django 2.1.4 on 2018-12-21 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20181221_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='icon',
        ),
    ]
