# Generated by Django 2.1.4 on 2018-12-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_author_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalheader',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
