# Generated by Django 2.1.4 on 2018-12-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20181224_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalheader',
            name='bg_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
