# Generated by Django 2.1.4 on 2018-12-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20181224_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bg_image',
            field=models.ImageField(upload_to='bg_images'),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_photo',
            field=models.ImageField(upload_to='profile_pictures'),
        ),
        migrations.AlterField(
            model_name='post',
            name='bg_img',
            field=models.ImageField(blank=True, null=True, upload_to='bg_images'),
        ),
    ]
