# Generated by Django 2.1.4 on 2019-01-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20190107_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalheader',
            name='content_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
