# Generated by Django 2.1.4 on 2019-01-14 08:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20190110_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalheader',
            name='text1',
        ),
        migrations.RemoveField(
            model_name='generalheader',
            name='text2',
        ),
        migrations.RemoveField(
            model_name='generalheader',
            name='text3',
        ),
        migrations.AddField(
            model_name='generalheader',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
